### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by CAESIUS-TIM** [gopaljigaur/Image2ASCII#2]
`acii` -> `ascii`

```shell
pipx install img2ascii
img2ascii ...
```

```log
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\26523\.local\bin\img2ascii.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'img2acii'
```

https://github.com/gopaljigaur/img2ascii/blob/7ba0d058f3fd12f94b737a59d3d0132dd69e6365/setup.py#L23

https://github.com/gopaljigaur/img2ascii/blob/7ba0d058f3fd12f94b737a59d3d0132dd69e6365/img2ascii.egg-info/entry_points.txt#L2

https://github.com/gopaljigaur/img2ascii/blob/7ba0d058f3fd12f94b737a59d3d0132dd69e6365/setup_tmp.py#L23

**Comment by gopaljigaur** [comment]
This typo has been fixed now, thank you for notifying me.
